namespace Move_specs;

public class Resolves
{
    private static readonly Blocks blocks = Blocks.Init();

    [Test]
    public void perfect_clear()
    {
        var field = Field.Parse(@"
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            XXXXX.XXXX
            XXXXX.XXXX
            XXXXX.XXXX
            XXXXX.XXXX");

        var block = blocks.Select(5, 0, Shape.I, Rotation.Right);
        var move = field.Move(block, isRotation: false);

        move.Field.Should().Be(@"
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........");

        move.Clearing.Should().Be(Clearing.Perfect(4));
    }

    [Test]
    public void Some_clear()
    {
        var field = Field.Parse(@"
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            XXXXX.XXXX
            XXXXX.X.XX
            XXXXX.XXXX");

        var block = blocks.Select(5, 0, Shape.I, Rotation.Right);
        var move = field.Move(block, isRotation: false);

        move.Field.Should().Be(@"
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            .....X....
            XXXXXXX.XX");

        move.Clearing.Should().Be(new Clearing(2));
    }

    [Test]
    public void no_clear()
    {
        var field = Field.Parse(@"
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            XXXXX.XXXX
            XXXXX.XXXX
            XXXXX.XXXX
            XXXXX.XXXX");

        var block = blocks.Select(5, 4, Shape.O);
        var move = field.Move(block, isRotation: false);

        move.Field.Should().Be(@"
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            .....XX...
            .....XX...
            XXXXX.XXXX
            XXXXX.XXXX
            XXXXX.XXXX
            XXXXX.XXXX");

        move.Clearing.Should().Be(Clearing.None);
    }

    [Test]
    public void t_spin()
    {
        var field = Field.Parse(@"
            ..........
            ..........
            ..........
            XXXX..XXXX
            XXXX...XXX
            XXXXX.XXXX
            XXXXX.XXXX");

        var block = blocks.Select(4, 1, Shape.T, Rotation.Uturn);
        var move = field.Move(block, isRotation: true);

        move.Field.Should().Be(@"
            ..........
            ..........
            ..........
            ..........
            ..........
            XXXX..XXXX
            XXXXX.XXXX");

        move.Clearing.Should().Be(Clearing.TSpin(2));
    }

    [Test]
    public void no_t_spin()
    {
        var field = Field.Parse(@"
            ..........
            ..........
            XXXX...XXX
            XXXX...XXX
            XXXXX.XXXX
            XXXXX.XXXX");

        var block = blocks.Select(4, 1, Shape.T, Rotation.Uturn);
        var move = field.Move(block, isRotation: true);

        move.Field.Should().Be(@"
            ..........
            ..........
            ..........
            ..........
            XXXX...XXX
            XXXXX.XXXX");

        move.Clearing.Should().Be(new Clearing(2));
    }
}
